# Generated by Django 4.1.6 on 2023-02-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("excited", "Excited"),
                            ("relaxed", "Relaxed"),
                            ("energized", "Energized"),
                        ],
                        max_length=10,
                    ),
                ),
                ("temperature", models.IntegerField()),
            ],
        ),
    ]
